---
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  piedpiper-flake8-gateway:
    lang: python3-flask
    handler: ./piedpiper-flake8-gateway
    image: piedpiper-flake8-gateway:latest
    secrets:
    - storage-access-key
    - storage-secret-key
  piedpiper-flake8-function:
    lang: python3-flask
    handler: ./piedpiper-flake8-function
    image: piedpiper-flake8-function:latest
    secrets:
    - storage-access-key
    - storage-secret-key
